# dbt_project.yml

name: "medical_telegram_project"
version: "1.0"
config-version: 2

profile: "default"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  medical_telegram_project:
    staging:
      +schema: staging
      +materialized: view

    marts:
      +schema: marts
      +materialized: table
